apiVersion: v1
kind: Service
metadata:
  name: wildfire-detection-service
  namespace: wildfire-apps
spec:
  type: NodePort
  selector:
    app: wildfire-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
